/**
 * User Entity Schemas (OpenAPI)
 *
 * Defines the reusable OpenAPI schema objects for user profiles
 * and authentication tokens. These are referenced by path definitions
 * and auto-generated request schemas.
 *
 * @module routes/swagger/schemas/user.entity
 */

module.exports = {
  /** Public-facing user profile (sensitive fields stripped) */
  UserEntity: {
    type: 'object',
    description: 'The sanitized public user profile entity record.',
    properties: {
      _id: {
        type: 'string',
        example: '6a312a635cef44df5183204a',
        description: 'Unique database identifier generated by MongoDB'
      },
      name: {
        type: 'string',
        example: 'Omar',
        description: 'Full name of the registered user'
      },
      email: {
        type: 'string',
        format: 'email',
        example: 'omyassdar@mail.com',
        description: 'Unique primary email address'
      },
      createdAt: {
        type: 'string',
        format: 'date-time',
        example: '2026-06-16T13:00:00.000Z',
        description: 'Timestamp indicating when the account profile was provisioned'
      }
    }
  },

  /** JWT tokens returned after successful authentication */
  AuthTokenPayload: {
    type: 'object',
    description: 'Session authentication tokens issued upon successful verification.',
    properties: {
      token: {
        type: 'string',
        example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        description: 'Bearer JSON Web Token used to authorize protected microservice operations'
      },
      expiresIn: {
        type: 'integer',
        example: 86400,
        description: 'Token lifespan token validity duration expressed in seconds (e.g., 24 hours)'
      }
    }
  }
};
